env:
  es6: true
  node: true
extends:
  - airbnb-base-typescript-prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - dist
rules:
  import/prefer-default-export: 'off'
  no-restricted-syntax: 'off'